### ISSUE TITLE
Improve meta fetcher refer to metascraper

### ISSUE THREAD

**Issue by SettingDust** [extractus/article-extractor#311]
Use https://metascraper.js.org/ to fetch meta.
Convenience and with more meta. It's complex to maintain a set of rules

Negative: It's won't return metas as array. So that the url can't choose

**Comment by ndaidong** [comment]
@SettingDust hi friend, thank you for your suggestion.

It's good to keep the codebase as close to native as possible, so we can easily bring it to other platforms such as Deno, Bun, or even browser. 

MetaScrapper is cool, however we only need the basic meta data. And the way they get [author](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-author/index.js), [description](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-description/index.js),  [image](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-image/index.js) and [date](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-date/index.js) is based on the same principles as we do, there really isn't much of an improvement. Of course that library is in-depth, so it covers more cases than `article-parser`.

So I think it's better if we just steal some of its cool features, rather than depend on it :smile:

**Comment by SettingDust** [comment]
It's fine. Metascraper can fetch meta from jsonld that we haven't

**Comment by andremacola** [comment]
I think we can improve this

Sometimes the datePublished is not exactly in the `head` section like this big portal here: 

https://g1.globo.com/mundo/noticia/2023/01/17/o-promotor-com-a-cabeca-a-premio-pela-mais-poderosa-mafia-da-italia.ghtml

`<time itemprop="datePublished" datetime="2023-01-17T22:25:19.719Z"> 17/01/2023 19h25 </time>`

Libs like https://github.com/adbar/trafilatura/blob/master/trafilatura/metadata.py#L103 extract with a different algorithm that works great.

**Comment by ndaidong** [comment]
@andremacola thank you for your suggestion. I've used trafilatura for writing crawler few years ago. That's a good example to refer. 

Actually they use [htmldate](https://github.com/adbar/htmldate) to find date. `htmldate` meticulously search in the entire HTML content by using both XML parser and RegExp to detect date info. We can do something like that, with performance trade-off.
